### ISSUE TITLE
Error in predictCox

### ISSUE THREAD

**Issue by yusheng0104** [isobelbarrott/Landmarking#1]
Hi, 
I am testing your package, and found the following error:

"Error in predictCox(object$models[[iterC]], centered = FALSE, times = eventTimes,  : 
  Incorrect objectOne or several model parameters have been estimated to be NA "

By checking the output, and found my binary V1 got a "NA". 
     V0                        V1               V2                     V3                    V4                      V5 
      0.030168260        NA       2.448410479      -1.819749347     -19.038992586     -18.667799985 

How should I take care of this problem? Is that possible V1 has too many zero's? Only got 5 one's out of 10,000 rows.

Thank you

**Comment by isobelbarrott** [comment]
Hello,

It does sound like there is not enough observations with V1 equal to 1 to fit a coefficient, although I do not know what your dataset looks like.

**Comment by yusheng0104** [comment]
Is it possible for you to set the coefficient to 0 in your package instead
of throwing an error because of NAs, so that the program won't quit due to
the error?
Thanks,

Jason
